---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - autojump
  - git
  - tree
  - httpie
  - curl
  - wget
  - zsh
  - zsh-completions
  - fzf
  - fd
  - ripgrep
  - nano
  
# homebrew cask applications
cask_applications:
  - iterm2
  - docker
  - steam
  - balenaetcher
  - logitech-options
  - postman
  - sublime-text
  - dash
  - go2shell

downloads:
   zwift:
     name: Zwift
     url: http://cdn.zwift.com/app/ZwiftOSX.dmg
     dest: "{{general.local_home}}/Downloads/ZwiftOSX.dmg"

