---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - autojump
  - git
  - tree
  - httpie
  - curl
  - wget
  - zsh

# homebrew cask applications
cask_applications:
  - iterm2
  - docker
  - steam

downloads:
   #zwift:
   #  name: Zwift
   #  url: http://cdn.zwift.com/app/ZwiftOSX.dmg
   #  dest: "{{general.local_home}}/Downloads/ZwiftOSX.dmg"

