---
# getting my dotfile configuration

- name: setting up my dotfiles
  git:
    repo: https://github.com/xyleth/dotfiles.git
    dest: /Users/benprice/Code/dotfiles

- name: sym linking zshrc dot file
  file:
    src: "{{general.local_home}}/Code/dotfiles/dot.zshrc"
    dest: "{{general.local_home}}/.zshrc"
    state: link