---
# getting my dotfile configuration

- name: setting up my dotfiles
  git:
    repo: https://github.com/xyleth/dotfiles.git
    dest: /Users/benprice/Code/dotfiles

- name: sym linking zshrc dot file
  file:
    src: "{{general.local_home}}/Code/dotfiles/dot.zshrc"
    dest: "{{general.local_home}}/.zshrc"
    state: link

- name: sym linking functions dot file
  file:
    src: "{{general.local_home}}/Code/dotfiles/dot.functions"
    dest: "{{general.local_home}}/.functions"
    state: link

- name: sym linking aliases dot file
  file:
    src: "{{general.local_home}}/Code/dotfiles/dot.aliases"
    dest: "{{general.local_home}}/.aliases"
    state: link

- name: sym linking nano dot file
  file:
    src: "{{general.local_home}}/Code/dotfiles/dot.nanorc"
    dest: "{{general.local_home}}/.nanorc"
    state: link